-- Phase 6: background job pipeline outputs (search index, previews, PDF exports).
--
-- Search uses plain ILIKE over a denormalized text column rather than
-- Postgres full-text search (tsvector/GIN) — a deliberate scope-and-portability
-- call, not an oversight: tsvector features aren't reliably supported by
-- pg-mem (the in-memory engine the test suite runs against, same rationale
-- as Phase 2's base64-over-BYTEA choice), and ILIKE is plenty for this
-- project's scale. Swapping in tsvector later only touches this table and
-- the query in jobs/search.ts, not the job pipeline that populates it.
CREATE TABLE IF NOT EXISTS search_index (
  page_id TEXT PRIMARY KEY,
  content TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One-row-per-page cache of a short plain-text preview (e.g. for a future
-- "recent pages" list), regenerated by the preview job after every persisted
-- update rather than computed on every read.
CREATE TABLE IF NOT EXISTS page_previews (
  page_id TEXT PRIMARY KEY,
  preview TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Generated export artifacts (currently just PDF). Stored as base64 TEXT,
-- same rationale as ops_log/snapshots in Phase 2 — sidesteps BYTEA
-- portability quirks at a storage-cost tradeoff that's irrelevant for
-- occasionally-generated exports.
CREATE TABLE IF NOT EXISTS exports (
  id TEXT PRIMARY KEY,
  page_id TEXT NOT NULL,
  format TEXT NOT NULL,
  data TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS exports_page_idx ON exports (page_id, created_at DESC);
